name: 测试邮件功能

on:
  # 手动触发测试
  workflow_dispatch:
  
  # 推送时自动测试（可选）
  push:
    branches: [ main, master ]
    paths:
      - 'utils_email.py'
      - 'test_email.py'
      - '.github/workflows/test-email.yml'

jobs:
  test-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install secure-smtplib
    
    - name: 测试邮件发送
      env:
        QQ_EMAIL: ${{ secrets.QQ_EMAIL }}
        AUTH_CODE: ${{ secrets.AUTH_CODE }}
        RECEIVER: ${{ secrets.RECEIVER }}
      run: |
        echo "开始测试邮件功能..."
        python test_email.py
        echo "邮件测试完成！"
    
    - name: 显示测试结果
      if: always()
      run: |
        echo "邮件功能测试状态: ${{ job.status }}"
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ 邮件功能正常，可以接收买卖信号提醒"
        else
          echo "❌ 邮件功能异常，请检查配置"
          echo "请确认以下设置："
          echo "1. QQ邮箱已开启SMTP服务"
          echo "2. 使用正确的SMTP授权码（不是QQ密码）"
          echo "3. 收件人邮箱地址正确"
        fi